### ISSUE TITLE
add chinese simple lookup test

### ISSUE THREAD

**Issue by balmas** [alpheios-project/selenium-tests#17]
we should add a simple lookup test for Chinese

**Comment by irina060981** [comment]
Lookup chinese (with upload cedict data request) via lookup box is ready.

But there are unknown problems with lookup by click and move,
This type of tests are postponed.
do you agree, @balmas ?

**Comment by balmas** [comment]
ok, but can you clarify what the "unknown problems" are?

**Comment by irina060981** [comment]
>ok, but can you clarify what the "unknown problems" are?

it simply doesn't work - click at the word doesn't execute anything - nor action, nor error
and it doesn't work only for chinese - all other languages could be clicked without any problems

**Comment by balmas** [comment]
does it work manually? Is it only on selenium that it fails?

**Comment by irina060981** [comment]
> does it work manually? Is it only on selenium that it fails?

yes it works manually
I believe that for some unknown reasons selection is not created by click on the specific HTML element (located by span with id) by Selenium

**Comment by balmas** [comment]
hmm. ok. then yes I think it can wait. Can you enter an issue here in the selenium tests repo so that we can come back to it at some point? thank you!

**Comment by irina060981** [comment]
ok
