### ISSUE TITLE
add treebank lookup test

### ISSUE THREAD

**Issue by balmas** [alpheios-project/selenium-tests#20]
add a test which does the following:

- clicks on a word which has treebank data
- verify that the popup has a disamibugated lexeme
- verify that the popup has a treebank icon
- verify that clicking on the treebank icon brings up the tree diagram

For use in this test, in #19 the following has been added to the index-qa.html file:

```
  <h4>Treebank Data</h4>
    <div lang="lat" class="alpheios-enabled" data-alpheios_tb_app="perseids-treebank-template"
         data-alpheios_tb_app_version="1"
         data-alpheios_tb_app_url="https://trees.alpheios.net/embed/DOC/SENTENCE"
         data-alpheios_tb_doc="phi0959.phi006.alpheios-text-lat1">

      <p data-alpheios_tb_sent="2">adspirate meis <span id="lat-tb-word">primaque</span> ab origine mundi</p>
    </div>
```

the word with the id 'lat-tb-word' can be used for the test

**Comment by irina060981** [comment]
merged and closed
