### ISSUE TITLE
update browserstack suite to use a min/max for each browser

### ISSUE THREAD

**Issue by balmas** [alpheios-project/selenium-tests#21]
I'd like browserstack test suite to run against both the known minimum supported version of each browser and the most recently available version of each browser.

**Comment by irina060981** [comment]
Config was updated in https://github.com/alpheios-project/selenium-tests/pull/23
I would also list here test results for browsers:

**Comment by irina060981** [comment]
Latin simple lookup succsessfull:

Windows 10 - Firefox 77 beta - 67
Windows 8.1 - Firefox 77 beta - 67

Windows 10 - Chrome 83 - 63
Windows 8.1 - Chrome 83 - 63
OS X Catalina - Chrome 83 - 63
OS X Mojave - Chrome 83 - 63

OS X High Sierra - safari 11.1
OS X Mojave - safari 12.1
OS X Catalina - safari 13.1

**Comment by irina060981** [comment]
**Greek simple lookup** succsessfull:

Windows 10 - Firefox 77 beta - 67
Windows 8.1 - Firefox 77 beta - 67
OS X High Sierra- Firefox 77 beta - 67
OS X Mojave - Firefox 77 beta - 67
OS X Catalina - Firefox 77 beta - 67

OS X Catalina - Chrome 83 - 63
OS X Mojave - Chrome 83 - 63
OS X High Sierra - Chrome 83 - 63

**Comment by irina060981** [comment]
**Arabic simple lookup** succsessfull:

Windows 10 - Firefox 77 beta - 67
Windows 8.1 - Firefox 77 beta - 67
OS X High Sierra- Firefox 77 beta - 67
OS X Mojave - Firefox 77 beta - 67
OS X Catalina - Firefox 77 beta - 67

Windows 10 - Chrome 83 - 63
Windows 8.1 - Chrome 83 - 63
OS X Catalina - Chrome 83 - 63
OS X Mojave - Chrome 83 - 63
OS X High Sierra - Chrome 83 - 63

// OS X High Sierra - safari 11.1 - this fails, it works very-very slowly and fails on changing language to arabic

OS X Mojav
OS X Mojave - safari 12.1
OS X Catalina - safari 13.1

**Comment by irina060981** [comment]
**Persian simple lookup** succsessfull:

Windows 10 - Firefox 77 beta - 67
Windows 8.1 - Firefox 77 beta - 67
OS X High Sierra- Firefox 77 beta - 67
OS X Mojave - Firefox 77 beta - 67
OS X Catalina - Firefox 77 beta - 67

OS X Catalina - Chrome 83 - 63
OS X Mojave - Chrome 83 - 63
OS X High Sierra - Chrome 83 - 63

**Comment by irina060981** [comment]
**Check initial actions** succsessfull:

Windows 10 - Firefox 77 beta - 67
Windows 8.1 - Firefox 77 beta - 67

Windows 10 - Chrome 83 - 63
Windows 8.1 - Chrome 83 - 63
OS X High Sierra - Chrome 83 - 63
OS X Catalina - Chrome 83 - 63
OS X Mojave - Chrome 83 - 63

**Comment by irina060981** [comment]
**Ancient Ethiopic (Ge'ez) simple lookup** succsessfull:

Windows 10 - Firefox 77 beta - 67
Windows 8.1 - Firefox 77 beta - 67
OS X High Sierra- Firefox 77 beta - 67
OS X Mojave - Firefox 77 beta - 67
OS X Catalina - Firefox 77 beta - 67

Windows 10 - Chrome 83 - 63
Windows 8.1 - Chrome 83 - 63
OS X Catalina - Chrome 83 - 63
OS X Mojave - Chrome 83 - 63
OS X High Sierra - Chrome 83 - 63

// OS X High Sierra - safari 11.1 - this fails, it works very-very slowly and fails on changing language 
OS X Mojave - safari 12.1
OS X Catalina - safari 13.1

**Comment by irina060981** [comment]
**Latin  no result lookup** succsessfull:

Windows 10 - Firefox 77 beta - 67
Windows 8.1 - Firefox 77 beta - 67

Windows 10 - Chrome 83 - 63
Windows 8.1 - Chrome 83 - 63Mojave

**Comment by irina060981** [comment]
**Syriac simple lookup** succsessfull:

Windows 10 - Firefox 77 beta - 67
Windows 8.1 - Firefox 77 beta - 67
OS X Catalina - Firefox 77 beta - 67
OS X Mojave - Firefox 77 beta - 67
OS X High Sierra- Firefox 77 beta - 67

Windows 10 - Chrome 83 - 63
Windows 8.1 - Chrome 83 - 63
OS X Catalina - Chrome 83 - 63
OS X Mojave - Chrome 83 - 63
OS X High Sierra - Chrome 83 - 63

// OS X High Sierra - safari 11.1 - this fails, it works very-very slowly and fails on changing language
OS X Mojave - safari 12.1
OS X Catalina - safari 13.1

**Comment by irina060981** [comment]
**Chinese simple lookup** succsessfull:

Windows 10 - Chrome 83 - 69
Windows 8.1 - Chrome 83 - 69
 
68-63 couldn't upload cedict
fails with the following error
![image](https://user-images.githubusercontent.com/12377640/83841803-e9c77880-a744-11ea-8047-760f37d648c2.png)

as I could see Array.prototype.flat is not supported in these versions
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

**Comment by irina060981** [comment]
@balmas , I will continue with test of version compliance
I need to finish with chinese, lookup by click test and treebank test

**Comment by balmas** [comment]
> **Chinese simple lookup** succsessfull:
> 
> Windows 10 - Chrome 83 - 69
> Windows 8.1 - Chrome 83 - 69
> OS X High Sierra - Chrome 83 - 69
> OS X Catalina - Chrome 83 - 69
> OS X Mojave - Chrome 83 - 69
> 
> 68-63 couldn't upload cedict
> fails with the following error
> ![image](https://user-images.githubusercontent.com/12377640/83841803-e9c77880-a744-11ea-8047-760f37d648c2.png)
> 
> as I could see `Array.prototype.flat` is not supported in these versions
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

Yes, I had seen this and am glad the tests caught it.  So we will make the minimum supported version 69 across the board.

**Comment by irina060981** [comment]
Chinese simple lookup succsessfull:

Windows 10 - Firefox 77 beta - 67
Windows 8.1 - Firefox 77 beta - 67
OS X Catalina - Firefox 77 beta - 67
OS X High Sierra - Chrome 83 - 69
OS X Mojave - Firefox 77 beta - 67

// OS X High Sierra - safari 11.1 - this fails, it works very-very slowly and fails on changing language
OS X Mojave - safari 12.1
OS X Catalina - safari 13.1

for firefox and safari we have the same browser's compability as for others tests

**Comment by irina060981** [comment]
**Simple click test (lat, grc, ara, per, gez, syr):**

Windows 10 - Firefox 77 beta - 67
Windows 8.1 - Firefox 77 beta - 67
OS X Catalina - Firefox 77 beta - 67

Windows 10 - Chrome 83 - 63
Windows 8.1 - Chrome 83 - 63
OS X Catalina - Chrome 83 - 63
OS X Mojave - Chrome 83 - 63

there are some problems with click test for chinese - 
so i would create a separate test for chinese click later

**Comment by balmas** [comment]
@irina060981 are we able to include any Mobile OS versions in the browser stack tests?

**Comment by irina060981** [comment]
>@irina060981 are we able to include any Mobile OS versions in the browser stack tests?

oh, It is great idea! will work on it - we need some updates for such tests

**Comment by irina060981** [comment]
**Treebank lookup test**:
Windows 10 - Firefox 77 beta - 67
Windows 8.1 - Firefox 77 beta - 67

**Comment by irina060981** [comment]
**Android**
Samsung Galaxy S20 Ultra (chrome)

Check Initial Actions - ok
Click lookup (lat, grc, ara, syr, per, gez) - ok
Latin lookup - ok
Latin lookup (no result) - ok
Greek lookup - ok
Arabic lookup - ok
Persian lookup - ok
Geez lookup - ok
Syriac lookup - ok
Chinese lookup - ok

**Comment by irina060981** [comment]
**IOS**
iPhone 11 Pro Max (chrome)

Check Initial Actions - ok
Click lookup (lat, grc, ara, syr, per, gez) - ok
Latin lookup - ok
Latin lookup (no result) - ok
Greek lookup - ok
Arabic lookup - ok
Persian lookup - ok
Geez lookup - ok
Syriac lookup - ok
Chinese lookup - ok

**Comment by irina060981** [comment]
I have fully tested with all tests 
(latin, latin (no result), greek, ara, per, syr, gez, zho, initial, simple click all langs besides zho) 
the following devices:

iPhone XS ios 13 (chrome, safari)
iPhone XS ios 12 (chrome, safari)
iPhone 11 Pro Max ios 13 (chrome, safari)
iPad Pro 11 2018 ios 12 (chrome, safari)

Samsung Galaxy S20 Plus android 10.0 (chrome, firefox)
Google Pixel 4 android 10.0 (chrome, firefox)
Xiaomi Redmi Note 7 android 9.0 (chrome, firefox)

I think that we have a good support by mobile devices.

**Comment by balmas** [comment]
Excellent. Thank you!
