### ISSUE TITLE
update broken tests

### ISSUE THREAD

**Issue by balmas** [alpheios-project/selenium-tests#22]
most of the tests in the browserstack suite are failing with the latest Alpheios code from the qa branch. It seems like they are mostly due changes in element ids or output.

```
    NoSuchElementError: Unable to locate element: *[id="alpheios-lookup-form-input"]
```

```
 Check text - "ferus fera ferum", was not found in the source - "1
    ferusferaferum
```

**Comment by irina060981** [comment]
Bug is fixed and also I have updated `demo/index.html` with Chinese and Syriac texts
Merged and closed
